bug: 58032 - Servlet initialization fails because JUnit is not available
Added exception handling for NoClassDefFoundError around
callsites to ZimbraSuite.addTest().

http://bugzilla.zimbra.com/show_bug.cgi?id=58032

Copied from Perforce
 Change: 282065